remove_sections:
  - bcftools-stats_singletones
  - bcftools-stats_sequencing_depth
  - bcftools-stats_sites_per_sample
  - bcftools-stats_ts_tv
  - bcftools-stats_depth_plot
  - samtools-stats
table_columns_visible:
  verifybamid-results_table:
    verifybamid-READS: false
custom_data:
  peddy_relatedness:
    file_format: tsv
    section_name: "Peddy Relatedness"
    description: "Rate of allele sharing between samples (higher indicates greater relatedness)."
    plot_type: table
    pconfig:
      namespace: peddy_relatedness
      sort_rows: false
      col1_header: Pair_ID
    headers:
      Pair_ID:
        title: Pair
      Sample_A:
        title: Sample A
      Sample_B:
        title: Sample B
      Peddy_Relatedness:
        title: Relatedness
        format: "{:.3f}"
        scale: "Spectral"
        min: 0
        max: 0
plots_force_interactive: true
report_section_order:
  peddy_relatedness:
    order: 1000
table_cond_formatting_rules:
  peddy_relatedness-Peddy_Relatedness:
    fail:
      - gt: 0.5
    warn:
      - gt: 0.25
    pass:
      - lt: 0.25
