remove_sections:
  - bcftools-stats_singletones
  - bcftools-stats_sequencing_depth
  - bcftools-stats_sites_per_sample
  - bcftools-stats_ts_tv
  - bcftools-stats_depth_plot
  - samtools-stats
table_columns_visible:
  verifybamid-results_table:
    verifybamid-READS: false